-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgFEzAB16a1bMbNUuk
iltwDCbL5T5VamcMTlpHjbhxfSugCgYIKoZIzj0DAQehRANCAASu7lsfWxde5pM7
YQDRrr1oNXLxAE0oNKwHGmGMoiz6kFUlpUxxmAOw/BQdWi+B4LuGL0303tVNoRhL
tZ3IoMmD
-----END PRIVATE KEY-----